### ISSUE TITLE
Bug: Perch generator suddenly crashes

### ISSUE THREAD

**Issue by bnhovde** [bnhovde/generator-fed-up#24]
`````` vents.js:85
      throw er; // Unhandled 'error' event
            ^
Error: ENOENT, no such file or directory '/Users/bard/.node/lib/node_modules/generator-cdd/app/templates/app/perch/templates/layouts/global/header.php'
    at Error (native)
    at Object.fs.openSync (fs.js:500:18)
    at Object.fs.readFileSync (fs.js:352:15)
    at _prepCopy (/Users/bard/.node/lib/node_modules/generator-cdd/node_modules/yeoman-generator/lib/actions/actions.js:37:17)
    at copy (/Users/bard/.node/lib/node_modules/generator-cdd/node_modules/yeoman-generator/lib/actions/actions.js:70:19)
    at module.exports.yeoman.generators.Base.extend.writing.copyApp (/Users/bard/.node/lib/node_modules/generator-cdd/app/index.js:170:22)
    at /Users/bard/.node/lib/node_modules/generator-cdd/node_modules/yeoman-generator/lib/base.js:409:16
    at processImmediate [as _immediateCallback] (timers.js:367:17)```
``````

**Comment by bnhovde** [comment]
Closed with 7b92480
